development:
  adapter: postgresql
  encoding: utf8
  database: book_list
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: book_list
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: book_list
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST